config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :conversations do
  	resources :messages

  	collection do
  		get :inbox
  		get :all, action: :index
  		get :sent
  		get :trash 
  	end
  end

  root to: 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_messageable

  def name
  	"User #{id}"
  end

  def mailboxer_email(object)
  	nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	def index
		@conversations = current_user.mailbox.conversations
	end

	def inbox
		@conversations = current_user.mailbox.inbox
		render action: :index
	end

	def sent
		@conversations = current_user.mailbox.sentbox
		render action: :index
	end

	def trash
		@conversatons = current_user.mailbox.trash
		render action: :index
	end

	def show
		@conversation = current_user.mailbox.conversations.find(params[:id])
		@conversation.mark_as_read(current_user)
		@message = Mailboxer::Message.new
	end

	def new
		@recipients = User.all - [current_user]
	end

	def create
		recipients = User.where(id: params[:user_ids])
		receipt = current_user.send_message(recipients, params[:body], params[:subject])
		redirect_to conversation_path(receipt.conversation)
	end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :set_conversation

	def create
		current_user.reply_to_conversation(
			@conversation, 
			params[:mailboxer_message][:body],
			nil,
			true,
			true,
			params[:mailboxer_message][:attachment]
		)
		redirect_to conversation_path(@conversation)
	end

	private
		def set_conversation
			@conversation = current_user.mailbox.conversations.find(params[:conversation_id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/index.html.erb
<h1>Conversations</h1>

<hr />

Inbox (<%= current_user.mailbox.inbox.unread(current_user).count %>)
All Conversations (<%= current_user.mailbox.conversations.count %>)
Sent (<%= current_user.mailbox.sentbox.count %>)
Trash (<%= current_user.mailbox.trash.count %>)

<hr />

Total: <%= @conversations.count %>

<% @conversations.each do |conversation| %>
	<div>
		<% if conversation.is_unread?(current_user) %>
			<strong><%= link_to conversation.subject, conversation_path(conversation) %></strong>
		<% else %>
			<%= link_to conversation.subject, conversation_path(conversation) %>
		<% end %>
	</div>
<% end %>

</br>
<%= link_to "New Conversation", new_conversation_path, class: "btn btn-primary" %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= form_tag conversations_path, method: :post do %>
	<div>
		<%= select_tag :user_ids, options_from_collection_for_select(@recipients, :id, :name), multiple: true %>
	</div>

	<div>
		<%= text_field_tag :subject, nil, placeholder: "Subject" %>
	</div>

	<div>
		<%= text_area_tag :body, nil, placeholder: "Leave a comment" %> 
	</div>

	<%= submit_tag %>
<% end %>

app/views/conversations/show.html.erb
<h1><%= @conversation.subject %></h1>

<h4>Participants</h4>
<% @conversation.participants.each do |participant| %>
	<div><%= participant.name %></div>
<% end %>

<hr />

<% @conversation.receipts_for(current_user).each do |receipt| %>
	<div>
		<div><%= receipt.message.sender.name %> commented: </div> 
		<p><%= receipt.message.body %></p>

		<% if receipt.message.attachment? %>
			<strong>Attachment</strong>
			<%= link_to receipt.message.attachment.file.filename, receipt.message.attachment.url, 
			target: :blank %>
		<% end %>
	</div>
<% end %>

<%= form_for @message, url: conversation_messages_path(@conversation) do |f| %>
	<div><%= f.text_area :body %></div>
	<div><%= f.file_field :attachment %></div>

	<%= submit_tag %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>InAppMessaging</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
  	 <p class="notice"><%= notice %></p>
  	 <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>